<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>money_label</name>
   <tag></tag>
   <elementGuidId>7d2b5702-433e-4848-8009-3e9e491b8e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'form_account_amount']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;form_account_amount&quot;]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_account_amount</value>
   </webElementProperties>
</WebElementEntity>
